# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf203d2ad326e675fccbc7a98dc5bf9f4ae8595b49507625ae5080b84894098921dcbd89af37e6b91c28384696797fe5e86b0035b46febbc3cd86eb8c48fce2

test:
  secret_key_base: 131212071cc26a5073fd2024e00b08894ee1ed847ddc7c852f16afdb466642bca7d94789ec2c3b8c5934c1e9e02db2f72e236bdafdba67ccb2a7dbdd13efd9ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
